server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.250.96.180:5432/nrdsdev
    username: nrdsuser
    password: Pass1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # ? Controls how Hibernate creates/updates tables
    hibernate:
      ddl-auto: update

    # Optional: Show SQL in logs
    show-sql: true

    # Optional: Format SQL for readability
    properties:
      hibernate.format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
