server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: testdb
    password: testdb
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: TESTDB
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
